export interface Aircraft {
  id: string;
  name: string;
  manufacturer: string;
  category: string;
  range: number; // nautical miles
  passengers: number;
  cruiseSpeed: number; // ktas
  cabinHeight: string; // ft/in
  cabinWidth: string; // ft/in
  baggage: number; // cu ft
  approxPrice: string; // USD
  approxPriceNum: number; // for sorting
}

export const aircraftList: Aircraft[] = [
  {
    id: "g700",
    name: "Gulfstream G700",
    manufacturer: "Gulfstream",
    category: "Ultra Long Range",
    range: 7500,
    passengers: 19,
    cruiseSpeed: 516,
    cabinHeight: "6'3\"",
    cabinWidth: "8'2\"",
    baggage: 195,
    approxPrice: "$78M",
    approxPriceNum: 78000000,
  },
  {
    id: "global7500",
    name: "Bombardier Global 7500",
    manufacturer: "Bombardier",
    category: "Ultra Long Range",
    range: 7700,
    passengers: 19,
    cruiseSpeed: 516,
    cabinHeight: "6'2\"",
    cabinWidth: "8'2\"",
    baggage: 195,
    approxPrice: "$75M",
    approxPriceNum: 75000000,
  },
  {
    id: "longitude",
    name: "Cessna Citation Longitude",
    manufacturer: "Cessna",
    category: "Super-Midsize",
    range: 3500,
    passengers: 12,
    cruiseSpeed: 476,
    cabinHeight: "6'0\"",
    cabinWidth: "6'1\"",
    baggage: 106,
    approxPrice: "$27M",
    approxPriceNum: 27000000,
  },
  {
    id: "falcon8x",
    name: "Dassault Falcon 8X",
    manufacturer: "Dassault",
    category: "Ultra Long Range",
    range: 6450,
    passengers: 16,
    cruiseSpeed: 482,
    cabinHeight: "6'2\"",
    cabinWidth: "8'6\"",
    baggage: 230,
    approxPrice: "$58M",
    approxPriceNum: 58000000,
  },
  {
    id: "praetor600",
    name: "Embraer Praetor 600",
    manufacturer: "Embraer",
    category: "Super-Midsize",
    range: 4018,
    passengers: 12,
    cruiseSpeed: 466,
    cabinHeight: "6'0\"",
    cabinWidth: "6'9\"",
    baggage: 114,
    approxPrice: "$21.4M",
    approxPriceNum: 21400000,
  },
  {
    id: "pc24",
    name: "Pilatus PC-24",
    manufacturer: "Pilatus",
    category: "Light Jet",
    range: 2000,
    passengers: 10,
    cruiseSpeed: 440,
    cabinHeight: "5'0\"",
    cabinWidth: "5'9\"",
    baggage: 94,
    approxPrice: "$11.5M",
    approxPriceNum: 11500000,
  },
  {
    id: "hondajet",
    name: "HondaJet Elite II",
    manufacturer: "Honda Aircraft",
    category: "Very Light Jet",
    range: 1437,
    passengers: 7,
    cruiseSpeed: 422,
    cabinHeight: "4'9\"",
    cabinWidth: "5'0\"",
    baggage: 66,
    approxPrice: "$7M",
    approxPriceNum: 7000000,
  },
  {
    id: "kingair360",
    name: "Beechcraft King Air 360",
    manufacturer: "Beechcraft",
    category: "Turboprop",
    range: 1806,
    passengers: 11,
    cruiseSpeed: 312,
    cabinHeight: "4'9\"",
    cabinWidth: "4'6\"",
    baggage: 55,
    approxPrice: "$9.2M",
    approxPriceNum: 9200000,
  },
  {
    id: "challenger350",
    name: "Bombardier Challenger 350",
    manufacturer: "Bombardier",
    category: "Super-Midsize",
    range: 3200,
    passengers: 10,
    cruiseSpeed: 470,
    cabinHeight: "6'1\"",
    cabinWidth: "7'2\"",
    baggage: 106,
    approxPrice: "$26.9M",
    approxPriceNum: 26900000,
  },
  {
    id: "g280",
    name: "Gulfstream G280",
    manufacturer: "Gulfstream",
    category: "Super-Midsize",
    range: 3600,
    passengers: 10,
    cruiseSpeed: 459,
    cabinHeight: "6'3\"",
    cabinWidth: "7'2\"",
    baggage: 120,
    approxPrice: "$24.5M",
    approxPriceNum: 24500000,
  },
  {
    id: "falcon2000lxs",
    name: "Dassault Falcon 2000LXS",
    manufacturer: "Dassault",
    category: "Large Cabin",
    range: 4000,
    passengers: 10,
    cruiseSpeed: 459,
    cabinHeight: "6'2\"",
    cabinWidth: "7'7\"",
    baggage: 131,
    approxPrice: "$33M",
    approxPriceNum: 33000000,
  },
  {
    id: "legacy500",
    name: "Embraer Legacy 500",
    manufacturer: "Embraer",
    category: "Midsize",
    range: 3125,
    passengers: 12,
    cruiseSpeed: 466,
    cabinHeight: "6'0\"",
    cabinWidth: "6'9\"",
    baggage: 123,
    approxPrice: "$19.5M",
    approxPriceNum: 19500000,
  },
];
